// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOTPqu12ipIXFIrUPwIJZdyY8Jfaw9gc',
    appId: '1:950706662472:web:cc752c889ea5d21809bc7d',
    messagingSenderId: '950706662472',
    projectId: 'test-6d756',
    authDomain: 'test-6d756.firebaseapp.com',
    storageBucket: 'test-6d756.appspot.com',
    measurementId: 'G-WSVL3FB70R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVDVorNkaYBFStptKa-vp-H1z2YbKFBs',
    appId: '1:950706662472:android:664bd0ba16370f6209bc7d',
    messagingSenderId: '950706662472',
    projectId: 'test-6d756',
    storageBucket: 'test-6d756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDteT2xXr4RQMwKYd-Tnyn_H1k1pC_BM2s',
    appId: '1:950706662472:ios:61f0d4b3aaaeded409bc7d',
    messagingSenderId: '950706662472',
    projectId: 'test-6d756',
    storageBucket: 'test-6d756.appspot.com',
    iosBundleId: 'com.example.firebasetest',
  );
}
